// Licensed to the LF AI & Data foundation under one
// or more contributor license agreements. See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership. The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License. You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package metrics

import (
	"github.com/prometheus/client_golang/prometheus"

	"github.com/milvus-io/milvus/pkg/v2/util/typeutil"
)

const (
	// Optimization action labels
	ActionIncreaseEfLabel    = "increase_ef"
	ActionDecreaseEfLabel    = "decrease_ef"
	ActionIncreaseNProbeLabel = "increase_nprobe"
	ActionDecreaseNProbeLabel = "decrease_nprobe"
	ActionRebuildSmallerMLabel = "rebuild_smaller_m"
	ActionRebuildLargerMLabel  = "rebuild_larger_m"

	// Issue type labels
	IssueHighLatencyLabel     = "high_latency"
	IssueLowRecallLabel       = "low_recall"
	IssueHighMemoryLabel      = "high_memory"
	IssueOverProvisionedLabel = "over_provisioned"

	// Result labels
	ResultSuccessLabel = "success"
	ResultFailureLabel = "failure"
	ResultRolledBackLabel = "rolled_back"
)

var (
	// QueryCoordOptimizationSuggestionsTotal tracks total optimization suggestions generated
	QueryCoordOptimizationSuggestionsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_suggestions_total",
			Help:      "Total number of optimization suggestions generated by auto tuner",
		}, []string{
			collectionIDLabelName,
			"action",
			"issue_type",
		})

	// QueryCoordOptimizationActionsTotal tracks applied optimization actions
	QueryCoordOptimizationActionsTotal = prometheus.NewCounterVec(
		prometheus.CounterOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_actions_total",
			Help:      "Total number of optimization actions applied",
		}, []string{
			collectionIDLabelName,
			"action",
			"result",
		})

	// QueryCoordOptimizationLatencyImprovement tracks latency improvements
	QueryCoordOptimizationLatencyImprovement = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_latency_improvement",
			Help:      "Latency improvement percentage after optimization (-1.0 to 1.0, negative is improvement)",
			Buckets:   prometheus.LinearBuckets(-1.0, 0.1, 20), // -1.0 to 1.0 in 0.1 increments
		}, []string{
			collectionIDLabelName,
			"action",
		})

	// QueryCoordOptimizationRecallChange tracks recall changes
	QueryCoordOptimizationRecallChange = prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_recall_change",
			Help:      "Recall change percentage after optimization (-1.0 to 1.0, positive is improvement)",
			Buckets:   prometheus.LinearBuckets(-0.2, 0.02, 20), // -0.2 to 0.2 in 0.02 increments
		}, []string{
			collectionIDLabelName,
			"action",
		})

	// QueryCoordOptimizationP95Latency tracks current P95 latency per collection
	QueryCoordOptimizationP95Latency = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_p95_latency_ms",
			Help:      "Current P95 query latency in milliseconds per collection",
		}, []string{
			collectionIDLabelName,
			"index_type",
		})

	// QueryCoordOptimizationMeanRecall tracks current mean recall per collection
	QueryCoordOptimizationMeanRecall = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_mean_recall",
			Help:      "Current mean recall per collection",
		}, []string{
			collectionIDLabelName,
			"index_type",
		})

	// QueryCoordOptimizationMemoryUsage tracks memory usage per collection
	QueryCoordOptimizationMemoryUsage = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_memory_usage_bytes",
			Help:      "Current memory usage in bytes per collection",
		}, []string{
			collectionIDLabelName,
			"index_type",
		})

	// QueryCoordOptimizationParameterValue tracks current parameter values
	QueryCoordOptimizationParameterValue = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_parameter_value",
			Help:      "Current parameter value (ef, nprobe, M, etc.)",
		}, []string{
			collectionIDLabelName,
			"parameter_name",
		})

	// QueryCoordOptimizationCheckDuration tracks optimization check duration
	QueryCoordOptimizationCheckDuration = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_check_duration_ms",
			Help:      "Duration of optimization check in milliseconds",
			Buckets:   []float64{100, 500, 1000, 2000, 5000, 10000, 30000},
		})

	// QueryCoordOptimizationEnabled tracks whether auto-tuning is enabled
	QueryCoordOptimizationEnabled = prometheus.NewGauge(
		prometheus.GaugeOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_enabled",
			Help:      "Whether auto-tuning is enabled (1 = enabled, 0 = disabled)",
		})

	// QueryCoordOptimizationSampleCount tracks number of samples collected
	QueryCoordOptimizationSampleCount = prometheus.NewGaugeVec(
		prometheus.GaugeOpts{
			Namespace: milvusNamespace,
			Subsystem: typeutil.QueryCoordRole,
			Name:      "optimization_sample_count",
			Help:      "Number of query samples collected per collection",
		}, []string{
			collectionIDLabelName,
		})
)

// RegisterOptimizationMetrics registers all optimization metrics
func RegisterOptimizationMetrics() {
	prometheus.MustRegister(QueryCoordOptimizationSuggestionsTotal)
	prometheus.MustRegister(QueryCoordOptimizationActionsTotal)
	prometheus.MustRegister(QueryCoordOptimizationLatencyImprovement)
	prometheus.MustRegister(QueryCoordOptimizationRecallChange)
	prometheus.MustRegister(QueryCoordOptimizationP95Latency)
	prometheus.MustRegister(QueryCoordOptimizationMeanRecall)
	prometheus.MustRegister(QueryCoordOptimizationMemoryUsage)
	prometheus.MustRegister(QueryCoordOptimizationParameterValue)
	prometheus.MustRegister(QueryCoordOptimizationCheckDuration)
	prometheus.MustRegister(QueryCoordOptimizationEnabled)
	prometheus.MustRegister(QueryCoordOptimizationSampleCount)
}
